config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  resources :emails, only: :create do 
    member do
      get :unsubscribe
    end
  end

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord

  validates :email, presence: true, length: { maximum: 100 }

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  default_scope -> { order('id DESC') }

  before_save :should_generate_new_friendly_id?, if: :title_changed?

  validates :username, presence: true, length: { maximum: 255 }
  validates :keycode, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :image, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 65536 }

  before_save :security
   
  private

    def security
      unless self.username == "aheil4250" && self.keycode == "BBhh19!!"
        redirect_to root_url
      end
    end

    def should_generate_new_friendly_id?
      title_changed?
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def create
    @email = Email.new(email_params)
    if @result = @email.save
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js { render :action => "emails" }
        flash.now[:notice] = "You've successfully been added to the email list!"
        EmailMailer.success_email(@email).deliver_now
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js { render :action => "emails" }
        flash.now[:alert] = "You've failed!"
      end
    end
  end

  def unsubscribe
    @email = Email.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def email_params
      params.require(:email).permit(:email)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #before_action :authenticate_admin!, except: [:index, :show, :new, :edit]

  def index
    @posts = Post.all.reorder("created_at desc")
    @email = Email.new
  end

  def show
    @post = Post.friendly.find(params[:id])
    @recent_posts = Post.all.reorder("created_at desc").limit(2)
    @email = Email.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "You just created " + @post.title + "!"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'Whoa! Something went wrong!'
      render 'new'
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Good job!"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = 'Bad job!'
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id]).destroy
    redirect_to root_url
    flash[:notice] = "Delete successful."
  end

  private

    def authenticate_admin!
      @post = Post.friendly.find(params[:id])
      unless @post.username == "aheil4250" && @post.keycode == "BBhh19!!"
        redirect_to root_url
        flash[:notice] = "You do not have access to this page."
      end
    end

    def post_params
      params.require(:post).permit(:username, :keycode, :title, :image, :image_bottom, :image_square, :image_credit, :image_bottom_credit, :image_square_credit, :tagline, :content, :color, :readtime, :element)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @email = Email.new
    @recent_posts = Post.all.reorder("created_at desc").limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "The Zen Woods"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <meta name="theme-color" content="#c05a5a" />
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= render 'partials/themes' %>
    <%= render 'partials/twitter_cards' %>
    <%= render 'partials/analytics' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121678067-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121678067-1');
</script>

app/views/partials/_blog_twitter_cards.html.erb
<% content_for :blog_og_header do %>
  <meta property="og:url" content="<%= post_url(@post) %>" />
  <meta property="og:title" content="<%= @post.title %>" />
  <meta property="og:description" content="<%= truncate(@post.tagline, length: 140) %>" />
  <meta property="og:image" content="<%= @post.image %>" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="<%= @post.title %>" />
  <meta name="twitter:description" content="<%= truncate(@post.tagline, length: 140) %>" />
  <meta name="twitter:image" content="<%= @post.image %>" />
  <meta name="twitter:url" content="<%= post_url(@post) %>" />
  <meta name="twitter:site" content="@thezenwoods" />
  <meta name="twitter:creator" content="@thezenwoods" />
<% end %>

app/views/partials/_footer.html.erb
<footer class="full-footer-container wrapper">
  <div class="container">
    <div class="footer-disclaimer home-text center">
      Follow us on: <a class="instagram" href="https://instagram.com/thezenwoods">Instagram</a> | <a class="twitter" href="https://twitter.com/thezenwoods">Twitter</a> | <a class="pinterest" href="https://pinterest.com/thezenwoods">Pinterest</a>
    </div>
    <div class="footer-disclaimer home-text center">
      Built in Buffalo, New York, United States of America, Earth.
    </div>
  </div>
</footer>

app/views/partials/_themes.html.erb
<% if @post.present? %>
  <meta name="theme-color" content="<%= @post.color %>" />
  <style>
    ::selection {
      background: #<%= @post.color %>;
    }
    a {
      color: #<%= @post.color %>;
    }
    .product-title-background {
      background: #<%= @post.color %>;
    }
    .element-background {
      background: #<%= @post.color %>;
    }
    .more-button {
      background: #<%= @post.color %>;
      border: 2px solid #<%= @post.color %>;
    }
    .more-button:hover {
      color: #<%= @post.color %>;
    }
    .search-button {
      background: #<%= @post.color %>;
      border: 2px solid #<%= @post.color %>;
    }
    .search-button:hover {
      color: #<%= @post.color %>;
    }
    .search-field {
      border: 2px solid #<%= @post.color %>;
    }
    .full-footer-container {
      background: #<%= @post.color %>;
    }
  </style>
<% end %>

app/views/partials/_twitter_cards.html.erb
<% if content_for?(:blog_og_header) %>
  <%= yield(:blog_og_header) %>
<% else %>
  <meta property="og:url" content="https://www.thezenwoods.com" />
  <meta property="og:title" content="The Zen Woods" />
  <meta property="og:description" content="Clean air to breathe. Pure water to drink. Eternal Sun to see. Healthy Earth to live." />
  <meta property="og:image" content="https://i.imgur.com/fRcWyIZ.jpg" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="The Zen Woods" />
  <meta name="twitter:description" content="Clean air to breathe. Pure water to drink. Eternal Sun to see. Healthy Earth to live." />
  <meta name="twitter:image" content="https://i.imgur.com/fRcWyIZ.jpg" />
  <meta name="twitter:url" content="https://www.thezenwoods.com" />
  <meta name="twitter:site" content="@thezenwoods" />
  <meta name="twitter:creator" content="@thezenwoods" />
<% end %>

app/views/posts/edit.html.erb
<%= provide(:title, "Edit Blog Post") %>

<div class="mid-text padding-vertical border-bottom center">
  Edit a blog post
</div>

<div class="padding-vertical">
  <%= form_for(@post, url: post_path) do |f| %>
    <div class="field">
      <%= f.text_field :username, value: nil, placeholder: "Username", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :keycode, value: nil, placeholder: "Keycode", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :title, placeholder: "Title", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image, placeholder: "Image", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_credit, placeholder: "Image credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_bottom, placeholder: "Image bottom", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_bottom_credit, placeholder: "Image bottom credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_square, placeholder: "Image square", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_square_credit, placeholder: "Image square credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :tagline, placeholder: "Tagline", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :readtime, placeholder: "Readtime", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :element, placeholder: "Element", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :color, placeholder: "Color", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_area :content, placeholder: "Content", class: "text-area" %>
    </div>

    <div class="actions">
      <%= f.submit "Update blog post", class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= provide(:title, "Posts") %>

<div class="header-container">
  <nav class="nav padding-vertical-large center">
    <div class="site-title">
      <%= link_to "The Zen Woods", root_url %>
    </div>
    <div class="padding-top-mini">
      Stress-free productivity.
    </div>
  </nav>
</div>

<div class="white-background padding-bottom-large">
  <div class="container">
    <div class="flex">
      <div class="seventy center">

        <% @posts.each do |post| %>
          <div class="sub-title padding-bottom">
            <%= link_to post.title, post_path(post), class: "home-post-link" %>
          </div>

          <div class="padding-bottom">
            Posted on <%= post.created_at.strftime("%m.%d.%Y") %> | <%= post.readtime %> minute read | <%= post.element %>
          </div>

          <img class="large-image" src="<%= post.image_bottom %>" width="100%" />

          <div class="padding-vertical">
            <%= post.tagline %>
          </div>

          <div class="padding-bottom-large">
            <%= link_to post_path(post) do %>
              <div class="more-button">
                Read more...
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="sub-title padding-bottom">
          What else can you do to make life better?
        </div>

        <div class="padding-bottom">
          Even the simpliest, easiest things can help make your life the best. Enter your email below, and we will help you now and in the future! (pssst... it's free!)
        </div>

        <span class="email_form_post"><%= render 'partials/emails/email_form_post' %></span>

      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= provide(:title, "Create Blog Post") %>

<div class="mid-text padding-vertical border-bottom center">
  Create a blog post
</div>

<div class="padding-vertical">
  <%= form_for(@post, url: posts_path) do |f| %>
  <div class="field">
      <%= f.text_field :username, value: nil, placeholder: "Username", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :keycode, value: nil, placeholder: "Keycode", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :title, placeholder: "Title", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image, placeholder: "Image", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_credit, placeholder: "Image credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_bottom, placeholder: "Image bottom", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_bottom_credit, placeholder: "Image bottom credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_square, placeholder: "Image square", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :image_square_credit, placeholder: "Image square credit", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :tagline, placeholder: "Tagline", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :readtime, placeholder: "Readtime", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :element, placeholder: "Element", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_field :color, placeholder: "Color", class: "text-field" %>
    </div>

    <div class="field">
      <%= f.text_area :content, placeholder: "Content", class: "text-area" %>
    </div>

    <div class="actions">
      <%= f.submit "Create blog post", class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= provide(:title, sanitize(@post.title)) %>

<%= render 'partials/blog_twitter_cards' %>

<div class="header-container">
  <nav class="nav padding-vertical-large center">
    <div class="site-title">
      <%= link_to "The Zen Woods", root_url %>
    </div>
    <div class="padding-top-mini">
      Stress-free productivity.
    </div>
  </nav>
</div>

<div class="padding-bottom">
  <div class="product-title-background">
    <div class="container">
      <div class="post-title white-text right padding-vertical">
        <%= @post.title %>
      </div>
    </div>
  </div>
</div>


<div class="container">

  <div class="padding-bottom center">
    Posted on <%= @post.created_at.strftime("%m.%d.%Y") %> | <%= @post.readtime %> minute read | <%= @post.element %>
  </div>

  <div class="image-container">
    <img class="large-image" src="<%= @post.image %>" width="100%" />
    <div class="bottom-left">
      <%= @post.image_credit %>
    </div>
  </div>

  <div class="sub-title center padding-vertical-large">
    <%= @post.tagline %>
  </div>

</div>


<div class="container">
  <div class="flex">

    <div class="seventy">
      <div class="best">
        <%= sanitize(@post.content) %>
      </div>
    </div>

  </div>
</div>

<div class="padding-vertical-large container">
  <div class="flex">
    <div class="seventy">

      <div class="sub-title padding-bottom">
        I want people to know about this!
      </div>

      <div class="padding-bottom">
        The more people willing to learn about our environment, the better our world will be. You're already making a difference, let's help your friends make a difference too! Choose your blue.
      </div>

      <div class="flex">
        <div class="fifty">
          <a onclick="javascript:window.open('https://www.facebook.com/sharer/sharer.php?u=<%= post_url(@post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)" class="facebook-button">Facebook</a>
        </div>

        <div class="fifty">
          <a onclick="javascript:window.open('https://twitter.com/share?text=<%= @post.title %> - &amp;url=<%= post_url(@post) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0)" class="twitter-button">Twitter</a>
        </div>
      </div>

    </div>
  </div>
</div>


<div class="padding-vertical element-background">
  <div class="container">
    
    <div class="image-container">
      <img class="large-image" src="<%= @post.image_bottom %>" width="100%" />
      <div class="bottom-left">
        <%= @post.image_bottom_credit %>
      </div>
    </div>

  </div>
</div>


<div class="padding-vertical-large container">
  <div class="flex">
    <div class="seventy">

      <div class="sub-title padding-bottom">
        Thanks for reading this far!
      </div>

      <div class="padding-bottom">
        We really do appreciate it! You must be pretty serious about helping out the planet if you just read an entire post for fun. Let's take it one step further. Enter your email below, and we will help you help the Earth now and in the future! (pssst... it's free!)
      </div>

      <span class="email_form_post"><%= render 'partials/emails/email_form_post' %></span>

    </div>
  </div>
</div>

<div class="padding-bottom-large container">
  <div class="flex">
    <div class="seventy">

      <% @recent_posts.each do |post| %>
        <div class="sub-title padding-bottom">
          <%= link_to post.title, post_path(post), class: "home-post-link" %>
        </div>

        <img class="large-image" src="<%= post.image_bottom %>" width="100%" />

        <div class="padding-vertical">
          <%= post.tagline %>
        </div>

        <div class="padding-bottom-large">
          <%= link_to post_path(post) do %>
            <div class="more-button">
              Read more...
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="sub-title center padding-bottom-large">
        <%= link_to "View more posts...", posts_path %>
      </div>

      <div class="sub-title padding-bottom">
        What else can you do to make life better?
      </div>

      <div class="padding-bottom">
        Even the simpliest, easiest things can help make your life the best. Enter your email below, and we will help you now and in the future! (pssst... it's free!)
      </div>

      <span class="email_form_post"><%= render 'partials/emails/email_form_post' %></span>

    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="back-second"></div>
<div class="background"></div>
<div class="back-third"></div>

<div class="center home-text padding-vertical-large">

  <div class="wrapper container">
    <div class="home-title">
      The Zen Woods
    </div>
    
    
    <div class="padding-top-mini">
      Stress-free productivity.
    </div>
    <div class="home-column-mini padding-top-large">
      The Zen Woods is the most comfy place on the Internet. While you're chilling here, you'll learn about being stress-free, or at least managing stress, being productive, time management, and most importantly, just making your life better in general.
    </div>
  </div>

</div>

<div class="center home-text padding-bottom-large">
  <div class="container">
    <span class="email_form"><%= render 'partials/emails/email_form' %></span>
  </div>
</div>

<div class="padding-vertical element-background">
  <div class="container">
    <div class="sub-title center">
      Let's make life better together.
    </div>
  </div>
</div>

<div class="white-background padding-vertical-large">
  <div class="container">
    <div class="flex">
      <div class="seventy center">

        <% @recent_posts.each do |post| %>
          <div class="sub-title padding-bottom">
            <%= link_to post.title, post_path(post), class: "home-post-link" %>
          </div>

          <div class="padding-bottom">
            Posted on <%= post.created_at.strftime("%m.%d.%Y") %> | <%= post.readtime %> minute read | <%= post.element %>
          </div>

          <img class="large-image" src="<%= post.image_bottom %>" width="100%" />

          <div class="padding-vertical">
            <%= post.tagline %>
          </div>

          <div class="padding-bottom-large">
            <%= link_to post_path(post) do %>
              <div class="more-button">
                Read more...
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="sub-title center">
          <%= link_to "View more posts...", posts_path %>
        </div>

      </div>
    </div>
  </div>

  <div class="container padding-top-large">
    <div class="flex">
      <div class="seventy center">

        <div class="sub-title padding-bottom">
          What else can you do to make life better?
        </div>

        <div class="padding-bottom">
          Even the simpliest, easiest things can help make your life the best. Enter your email below, and we will help you now and in the future! (pssst... it's free!)
        </div>

        <span class="email_form_post"><%= render 'partials/emails/email_form_post' %></span>

      </div>
    </div>
  </div>
</div>